# pyproject.toml

[build-system]
requires      = ["setuptools>=62.3.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cord-sdk"
version = "1.0.0"
description = "The Cord SDK for Python"
readme = "README.md"
authors = [{ name = "Nick Filippakis", email = "nickfil@cord.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
keywords = ["cord", "sdk", "server", "cord-sdk"]
dependencies = [
    "PyJWT",
    "requests"
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/getcord/sdk-python"
